spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongo
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      auto-offset-reset: earliest
    producer:
      group-id: group_id

topic:
  name:
    consumer: user.events

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: ["health", "prometheus", "info"]
